AehpartaSecurityBundle_login:
    pattern:  /login
    defaults: { _controller: AehpartaSecurityBundle:Login:login }

AehpartaSecurityBundle_login_check:
    pattern:   /login_check

AehpartaSecurityBundle_register:
    pattern:  /register
    defaults: { _controller: AehpartaSecurityBundle:Login:register }

AehpartaSecurityBundle_reset:
    pattern:  /reset
    defaults: { _controller: AehpartaSecurityBundle:Login:reset }

AehpartaSecurityBundle_logout:
    pattern:   /logout
