EDB\ContentBundle\Entity\Resource:
    type: entity
    table: null
    repositoryClass: EDB\ContentBundle\Entity\ResourceRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        title:
            type: string
            length: 255
        content:
            type: text

        deleted:
            type: boolean
        created:
            type: datetime
        modified:
            type: datetime

    lifecycleCallbacks:
        prePersist: [ onCreate ]
        preUpdate: [ onUpdate ]
