
EDBFrontpageBundle_:
    resource: "@EDBFrontpageBundle/Resources/config/routing.yml"
    prefix:   /

EDBContentBundle_:
    resource: "@EDBContentBundle/Resources/config/routing.yml"
    prefix:   /content

EDBBrowserBundle_:
    resource: "@EDBBrowserBundle/Resources/config/routing.yml"
    prefix:   /browser

AehpartaSecurityBundle_:
    resource: "@AehpartaSecurityBundle/Resources/config/routing.yml"
    prefix:   /security

AehpartaFormBundle_:
    resource: "@AehpartaFormBundle/Resources/config/routing.yml"
    prefix:   /afb

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
