parameters:
#    aehparta_response.example.class: Aehparta\ResponseBundle\Example

services:
#    aehparta_response.example:
#        class: %aehparta_response.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
